### ISSUE TITLE
Steering wheel initializes with large deadzone

### ISSUE THREAD

**Issue by jlillest** [her001/tmdrv#1]
Thanks for the great utility!  Using your script, I've been able to get the USB commands from the Thrustmaster Steering Wheel from all the buttons but I can't get any info off of the steering wheel.  Do you have any ideas on how to make this work?

I'm currently using SDL to read out the buttons, but I can read the same info from the command line.  Using the same thing, I see no packets being sent when using the wheel.

I'm unable to find any info on the USB endpoints you using to configure the device.  Do you have a manual for the device or other info you can share?

**Comment by her001** [comment]
If you turn the wheel far enough, you should be able to get values out of it. For some reason, it starts by default with a huge deadzone. Until I figure out exactly how to fix this, you can work around it by starting a race in Speed Dreams, which will eliminate the deadzone.

As for USB endpoints and configuration, right now no configuration is done. This may change later. For initialization, I send a couple control packets to the device. See [here](https://github.com/her001/tmdrv/blob/8062731947f6ea4a5ec2383d3596c97976d7947a/tmdrv.py#L50) and [here](https://github.com/her001/tmdrv/blob/8062731947f6ea4a5ec2383d3596c97976d7947a/tmdrv.py#L69). I knew I had to do this because of a USB packet capture I did between a Windows VM and Linux. I will work on uploading the capture file somewhere when I get the chance.

**Comment by jlillest** [comment]
Ok, cool, I see the deadzone now.  I can currently read the steering wheel with the deadzone using your utility to change modes.

Or, if I don't send the commands to the secondary device (044f:b65d) then I get the steering wheel output without the deadzone and the pedals act weird.  I get no signal off the clutch and the brake and gas pedals are on/off and don't provide a incremental value of how far they're pressed.

I'm going to poke around the speed dreams source to see if I can find what they're doing to calibrate the steering wheel.

**Comment by her001** [comment]
It appears to be a setting in the OS. The wheel still sends the turning data and Speed Dreams does not appear to send anything via usb.

**Comment by jlillest** [comment]
I'm unable to get anything to do anything with the haptics, so it appears we're going to switch devices.  It appears that logitech has good linux support, so we'll probably go that route.

Thanks for all the help!

**Comment by her001** [comment]
It now uses jscal to calibrate the wheel after initializing it, eliminating the deadzone issue.
